### ISSUE TITLE
Cannot get sidenav to default to closed on mobile

### ISSUE THREAD

**Issue by mikestefanello** [pratikborsadiya/vali-admin#36] opened 2018-02-25 22:26 UTC
First off, amazing work on this theme and thank you very much for making it available.

It works fine on your demo but locally, I cannot get the sidebar nav to default to be closed on small devices. Is there something extra I need to do?

Thanks

**Comment by pratikborsadiya** [comment] 2018-02-26 06:32
Hi Mike,

It seems that the code you are using is not up to date.
The issue is fixed in #28. Please make sure that code is up to date.

**Closed by pratikborsadiya** 2018-02-26 06:32 UTC
