### ISSUE TITLE
app-content sliding from left on page reload

### ISSUE THREAD

**Issue by ralberto** [pratikborsadiya/vali-admin#80] opened 2019-02-06 10:49 UTC
**Describe the bug**
While switching between pages on the left side menu, most of the times the app content shows an effect sliding from left to its position. 

**To Reproduce**
Using MSEdge access the demo site, i.e.: https://pratikborsadiya.in/vali-admin/

**Expected behavior**
Switch between options on menu maintains the position of the app-content panel.

**Desktop (please complete the following information):**
 - OS: Windows 10 EE
- Microsoft Edge 42.17134.1.0
- Microsoft EdgeHTML 17.17134

**Comment by pratikborsadiya** [comment] 2023-07-01 18:17
Not able to reproduce on latest version of Edge. Closing now.

**Closed by pratikborsadiya** 2023-07-01 18:17 UTC
